# Generated by Django 2.2.7 on 2019-12-06 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='isPopular',
            field=models.BooleanField(default=False, verbose_name='Показывать в популярных направлениях ?'),
        ),
    ]
