# Generated by Django 2.2.7 on 2019-11-25 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tour',
            old_name='name_lower',
            new_name='nameLower',
        ),
    ]
