# Generated by Django 2.2.7 on 2019-11-26 16:42

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0002_auto_20191125_2337'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Глобальный регион (например, Америка, Азия)')),
                ('nameLower', models.CharField(blank=True, max_length=255, null=True)),
                ('nameSlug', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Глобальный регион ',
                'verbose_name_plural': 'Глобальные регионы ',
            },
        ),
        migrations.CreateModel(
            name='TourVariant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Вид тура')),
                ('nameLower', models.CharField(blank=True, max_length=255, null=True)),
                ('nameSlug', models.CharField(blank=True, max_length=255, null=True)),
                ('pageH1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тег H1')),
                ('pageTitle', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название страницы SEO')),
                ('pageDescription', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание страницы SEO')),
                ('pageKeywords', models.TextField(blank=True, null=True, verbose_name='Keywords SEO')),
                ('pageSeoText', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Полное описание вида тура')),
            ],
            options={
                'verbose_name': 'Вид тура',
                'verbose_name_plural': 'Виды туров',
            },
        ),
        migrations.AddField(
            model_name='country',
            name='nameLower',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='nameSlug',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='nameLower',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='nameSlug',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resort',
            name='nameLower',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resort',
            name='nameSlug',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='isHot',
            field=models.BooleanField(default=False, verbose_name='Отображать на баннере?'),
        ),
        migrations.AddField(
            model_name='tourfood',
            name='nameLower',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tourfood',
            name='nameSlug',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='touroption',
            name='nameLower',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='touroption',
            name='nameSlug',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='town',
            name='nameLower',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='town',
            name='nameSlug',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.RemoveField(
            model_name='tour',
            name='food',
        ),
        migrations.AddField(
            model_name='tour',
            name='food',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tour.TourFood', verbose_name='Питание'),
        ),
        migrations.AddField(
            model_name='country',
            name='globalRegion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tour.GlobalRegion', verbose_name='Глобальный регион'),
        ),
        migrations.AddField(
            model_name='tour',
            name='variant',
            field=models.ManyToManyField(to='tour.TourVariant', verbose_name='Вид тура'),
        ),
    ]
