# Generated by Django 2.2.7 on 2019-11-27 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0003_auto_20191126_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tour.Country', verbose_name='Страна'),
        ),
    ]
