# Generated by Django 2.2.7 on 2019-11-27 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0004_tour_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='globalRegion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='global_region', to='tour.GlobalRegion', verbose_name='Глобальный регион'),
        ),
    ]
