# Generated by Django 2.2.7 on 2019-12-05 20:29

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tour', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeoTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indexTitle', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тег Title для главной')),
                ('indexDescription', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тег Description для главной')),
                ('indexKeywords', models.TextField(blank=True, null=True, verbose_name='Тег Keywords для главной')),
                ('servicesTitle', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тег Title для страницы со всеми услугами')),
                ('servicesDescription', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тег Description для страницы со всеми услугам')),
                ('servicesKeywords', models.TextField(blank=True, null=True, verbose_name='Тег Keywords для страницы со всеми услугам')),
                ('postsTitle', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тег Title для страницы со всеми статьями')),
                ('postsDescription', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тег Description для страницы со всеми статьями')),
                ('postsKeywords', models.TextField(blank=True, null=True, verbose_name='Тег Keywords для страницы со всеми статьями')),
                ('contactTitle', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тег Title для страницы контакты')),
                ('contactDescription', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тег Description для страницы контакты')),
                ('contactKeywords', models.TextField(blank=True, null=True, verbose_name='Тег Keywords для страницы контакты')),
                ('indexSeoText', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='СЕО тектс для главной')),
            ],
            options={
                'verbose_name': 'Теги и тексты для статических страниц',
                'verbose_name_plural': 'Теги и тексты для статических страниц',
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=1, verbose_name='Номер по порядку')),
                ('smallOffer', models.CharField(blank=True, max_length=20, null=True, verbose_name='Первый заголовок на баннере (чтобы выделить цветом слово или фразу используйте выражение : @@текст## )')),
                ('bigOffer', models.CharField(max_length=30, null=True, verbose_name='Заголовок на баннере (30 символов)')),
                ('smallText', models.CharField(blank=True, max_length=160, null=True, verbose_name='Описание на баннере (160 символов)')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='Картинка для баннера (1920 x (700-900))')),
                ('bannerUrl', models.CharField(blank=True, max_length=100, verbose_name='Произвольная ссылка с баннера')),
                ('isActive', models.BooleanField(default=True, verbose_name='Отображать баннер?')),
                ('tourUrl', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tour.Tour', verbose_name='Баннер ссылается на тур')),
            ],
            options={
                'verbose_name': 'Баннер',
                'verbose_name_plural': 'Баннеры',
            },
        ),
    ]
