# Generated by Django 2.2.7 on 2019-11-25 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=1, verbose_name='Номер по порядку')),
                ('bannerOffer', models.CharField(max_length=20, verbose_name='Категория баннера (20символов)')),
                ('bigTextColored', models.CharField(max_length=10, null=True, verbose_name='Заголовок на баннере выделенный цветом (10символов)')),
                ('bigText', models.CharField(max_length=30, null=True, verbose_name='Заголовок на баннере (30 символов)')),
                ('smallText', models.CharField(max_length=160, null=True, verbose_name='Описание на баннере (160 символов)')),
                ('image', models.ImageField(blank=True, upload_to='banners/', verbose_name='Картинка для баннера (1920 x (700-900))')),
                ('buttonText', models.CharField(max_length=10, verbose_name='Надпись на кнопке')),
                ('buttonUrl', models.CharField(max_length=100, verbose_name='Ссылка с кнопки')),
                ('isActive', models.BooleanField(default=True, verbose_name='Отображать баннер?')),
            ],
            options={
                'verbose_name': 'Баннер',
                'verbose_name_plural': 'Баннеры',
            },
        ),
        migrations.CreateModel(
            name='SeoTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indexTitle', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тег Title для главной')),
                ('indexDescription', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тег Description для главной')),
                ('indexKeywords', models.TextField(blank=True, null=True, verbose_name='Тег Keywords для главной')),
                ('servicesTitle', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тег Title для страницы со всеми услугами')),
                ('servicesDescription', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тег Description для страницы со всеми услугам')),
                ('servicesKeywords', models.TextField(blank=True, null=True, verbose_name='Тег Keywords для страницы со всеми услугам')),
                ('postsTitle', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тег Title для страницы со всеми статьями')),
                ('postsDescription', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тег Description для страницы со всеми статьями')),
                ('postsKeywords', models.TextField(blank=True, null=True, verbose_name='Тег Keywords для страницы со всеми статьями')),
                ('contactTitle', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тег Title для страницы контакты')),
                ('contactDescription', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тег Description для страницы контакты')),
                ('contactKeywords', models.TextField(blank=True, null=True, verbose_name='Тег Keywords для страницы контакты')),
            ],
            options={
                'verbose_name': 'Теги для статических страниц',
                'verbose_name_plural': 'Теги для статических страниц',
            },
        ),
    ]
