# Generated by Django 2.2.7 on 2019-12-05 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='smallOfferReplaced',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
