# Generated by Django 2.2.7 on 2019-11-26 16:42

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seotag',
            options={'verbose_name': 'Теги и тексты для статических страниц', 'verbose_name_plural': 'Теги и тексты для статических страниц'},
        ),
        migrations.AddField(
            model_name='seotag',
            name='indexSeoText',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='СЕО тектс для главной'),
        ),
    ]
