# Generated by Django 2.2.7 on 2019-11-27 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20191126_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='bannerOffer',
            field=models.CharField(blank=True, max_length=20, verbose_name='Категория баннера (20символов)'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='bigTextColored',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Заголовок на баннере выделенный цветом (10символов)'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='buttonText',
            field=models.CharField(blank=True, max_length=10, verbose_name='Надпись на кнопке'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='buttonUrl',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ссылка с кнопки'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(upload_to='banners/', verbose_name='Картинка для баннера (1920 x (700-900))'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='smallText',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='Описание на баннере (160 символов)'),
        ),
    ]
