# Generated by Django 2.2.7 on 2019-11-27 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0005_auto_20191127_0815'),
        ('pages', '0003_auto_20191127_0754'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='tourUrl',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tour.Tour', verbose_name='Кнопка ссылается на тур'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='buttonUrl',
            field=models.CharField(blank=True, max_length=100, verbose_name='Произвольная сылка с кнопки'),
        ),
    ]
