# Generated by Django 2.2.7 on 2019-12-06 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20191205_2338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='bannerUrl',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='tourUrl',
        ),
    ]
