# Generated by Django 2.2.7 on 2019-11-25 20:26

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, null=True, verbose_name='Название (40 символов)')),
                ('name_slug', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, upload_to='blog_img/', verbose_name='Изображение превью (555 x 390)')),
                ('page_h1', models.CharField(max_length=255, null=True, verbose_name='Тег H1')),
                ('page_title', models.CharField(max_length=255, null=True, verbose_name='Название страницы SEO')),
                ('page_description', models.CharField(max_length=255, null=True, verbose_name='Описание страницы SEO')),
                ('page_keywords', models.TextField(null=True, verbose_name='Keywords SEO')),
                ('short_description', models.CharField(max_length=100, verbose_name='Краткое описание (100 символов)')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Статья')),
                ('views', models.IntegerField(default=0, verbose_name='Просмотров')),
                ('is_at_index', models.BooleanField(db_index=True, default=True, verbose_name='Отображать статью на главной?')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Отображать статью в списке всех статей?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Статью',
                'verbose_name_plural': 'Статьи',
            },
        ),
    ]
