# Generated by Django 2.2.7 on 2019-11-25 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Callback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Нет данных', max_length=255, verbose_name='Имя')),
                ('phone', models.CharField(blank=True, default='Нет данных', max_length=255, verbose_name='Телефон')),
                ('email', models.CharField(blank=True, default='Нет данных', max_length=255, verbose_name='Почта')),
                ('service', models.CharField(blank=True, default='Нет данных', max_length=255, verbose_name='Услуга')),
                ('message', models.TextField(blank=True, default='Нет данных', verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата заполнения')),
            ],
            options={
                'verbose_name': 'Форма заказа звонка',
                'verbose_name_plural': 'Формы заказа звонка',
            },
        ),
    ]
