# Generated by Django 2.2.7 on 2019-11-26 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tour', '0003_auto_20191126_1942'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=5, verbose_name='Оценка')),
                ('commentText', models.TextField(null=True, verbose_name='Отзыв')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('commentFrom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_from', to=settings.AUTH_USER_MODEL, verbose_name='Отзыв от')),
                ('commentTour', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_tour', to='tour.Tour', verbose_name='Отзыв к туру')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
